# run with: $ docker-compose down && docker-compose up >server.log

version: '3'
services:

  mongo:
    image: mongo:4.2@sha256:1c2243a5e21884ffa532ca9d20c221b170d7b40774c235619f98e2f6eaec520a
    command: mongod --port 27017
    ports:
      - "27017:27017"
    logging:
      driver: none

  api:
    depends_on:
      - mongo
    image: node:12
    user: node
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: bash -c "echo 'npm install' && npm install && echo 'npm start' && npm start"
    environment:
      JWT_KEY: "secret"
      PORT: 3000
      MONGODB_URI: "mongodb://mongo:27017"

  tests:
    depends_on:
      - mongo
      - api
    image: node:12
    user: "node"
    restart: "no"
    working_dir: /home/node/tests
    volumes:
      - /Users/adrienjoly/dev/adrienjoly/cours-nodejs-project-solution:/home/node/tests:ro
    command: bash -c "echo 'waiting for server...' && npx wait-on tcp:api:3000 && echo 'starting tests...' && npm run --silent test:e2e"
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
      API_URL: "http://api:3000"
    